In [44]:
import pandas as pd
import numpy as np

In [45]:
import plotly.express as px
import plotly.graph_objects as go

In [46]:
import plotly.io as pio
pio.renderers.default = 'browser'  # Stable in VS Code/Jupyter without mime renderer issues

In [47]:
import sys
!{sys.executable} -m pip install --upgrade nbformat

Requirement already satisfied: nbformat in d:\code\.venv\Lib\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in d:\code\.venv\Lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in d:\code\.venv\Lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in d:\code\.venv\Lib\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in d:\code\.venv\Lib\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in d:\code\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\code\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in d:\code\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in d:\code\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in d:\code\.venv\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.2)

In [48]:
cordinate=pd.read_csv(r"C:\Users\DELL\Downloads\district wise centroids.csv")

In [49]:
cordinate.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [50]:
distic=pd.read_csv(r"C:\Users\DELL\Downloads\india-districts-census-2011.csv")

In [51]:
distic.head()

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629

In [52]:
cordinate.shape

(594, 4)

In [53]:
distic.shape

(640, 118)

In [54]:
cordinate.isnull().sum()

State        0
District     0
Latitude     0
Longitude    0
dtype: int64

In [55]:
distic.isnull().sum()

District code                    0
State name                       0
District name                    0
Population                       0
Male                             0
                                ..
Power_Parity_Rs_330000_425000    0
Power_Parity_Rs_425000_545000    0
Power_Parity_Rs_330000_545000    0
Power_Parity_Above_Rs_545000     0
Total_Power_Parity               0
Length: 118, dtype: int64

In [56]:
distic.duplicated().sum()

np.int64(0)

In [57]:
col = [
    'District code', 'District name', 'Population', 'Male', 'Female', 
    'Literate', 'Households_with_Internet', 'Housholds_with_Electric_Lighting', 
    'LPG_or_PNG_Households', 'Graduate_Education'
]

temp = distic[col]

In [58]:
temp.head()

,District code,District name,Population,Male,Female,Literate,Households_with_Internet,Housholds_with_Electric_Lighting,LPG_or_PNG_Households,Graduate_Education
0,1,Kupwara,870354,474190,396164,439654,762,83071,15828,21751
1,2,Badgam,753745,398041,355704,335649,1999,90190,15118,27950
2,3,Leh(Ladakh),133487,78971,54516,93770,574,17250,13645,6197
3,4,Kargil,140802,77785,63017,86236,235,15824,3285,3077
4,5,Punch,476835,251899,224936,261724,346,62900,13160,13962

In [59]:
cordinate.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [60]:
final=cordinate.merge(temp,left_on='District',right_on='District name').drop(columns=['District name'])

In [61]:
final.head()

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,Housholds_with_Electric_Lighting,LPG_or_PNG_Households,Graduate_Education
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,566108,194954,100226
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,897970,223016,144915
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,944555,324406,246409
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,1297273,479914,263023
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,1186028,648568,221924

In [62]:
final['sex_ratio']=round((final['Female']/final['Male'])*100)

In [63]:
final.head()

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,Housholds_with_Electric_Lighting,LPG_or_PNG_Households,Graduate_Education,sex_ratio
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,566108,194954,100226,100.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,897970,223016,144915,98.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,944555,324406,246409,100.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,1297273,479914,263023,101.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,1186028,648568,221924,100.0

In [64]:
final['literacy_rate']=round((final['Literate']/final['Population'])*100)

In [65]:
final.head()

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,Housholds_with_Electric_Lighting,LPG_or_PNG_Households,Graduate_Education,sex_ratio,literacy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,566108,194954,100226,100.0,54.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,897970,223016,144915,98.0,57.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,944555,324406,246409,100.0,64.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,1297273,479914,263023,101.0,64.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,1186028,648568,221924,100.0,61.0

In [66]:
final['Graduate_rate']=round(final['Graduate_Education']/final['Literate']*100)

In [67]:
final.head()

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,Housholds_with_Electric_Lighting,LPG_or_PNG_Households,Graduate_Education,sex_ratio,literacy_rate,Graduate_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,566108,194954,100226,100.0,54.0,7.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,897970,223016,144915,98.0,57.0,6.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,944555,324406,246409,100.0,64.0,9.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,1297273,479914,263023,101.0,64.0,8.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,1186028,648568,221924,100.0,61.0,7.0

In [68]:
final.drop(columns=['Male','Female','Literate','Graduate_Education'],inplace=True)

In [69]:
final.head()

,State,District,Latitude,Longitude,District code,Population,Households_with_Internet,Housholds_with_Electric_Lighting,LPG_or_PNG_Households,sex_ratio,literacy_rate,Graduate_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,5512,566108,194954,100.0,54.0,7.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,8606,897970,223016,98.0,57.0,6.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,13763,944555,324406,100.0,64.0,9.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,22411,1297273,479914,101.0,64.0,8.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,19383,1186028,648568,100.0,61.0,7.0

In [70]:
final.to_csv('india',index=False)

In [71]:
list_of_state=list(final['State'].unique())

In [72]:
list_of_state.insert(0,'Overall India')

In [73]:
list_of_state

['Overall India',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Daman and Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Orissa',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttaranchal',
 'West Bengal']

In [74]:
sorted(final.columns[5:])

['Graduate_rate',
 'Households_with_Internet',
 'Housholds_with_Electric_Lighting',
 'LPG_or_PNG_Households',
 'Population',
 'literacy_rate',
 'sex_ratio']

In [75]:
import plotly.express as px
df = px.data.carshare()
fig = px.scatter_map(df, lat="centroid_lat", lon="centroid_lon",     color="peak_hour", size="car_hours",
                  color_continuous_scale=px.colors.cyclical.IceFire, size_max=15, zoom=10)
fig.show()

In [79]:
fig = px.scatter_mapbox(cordinate, lat="Latitude", lon="Longitude", zoom=3,
                             mapbox_style="carto-positron")
fig.show()

C:\Users\DELL\AppData\Local\Temp\ipykernel_27752\322145642.py:1: DeprecationWarning:

*scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/